# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup

      - name: Lint project
        run: yarn run lint

      - name: Type check project
        run: yarn run typecheck

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup

      - name: Test
        run: yarn run test
